import type { Metadata } from "next";
import "./globals.scss";



export const metadata: Metadata = {
  title: "Bytebank",
  description: "Generated by Victor Carnevale Fornaziero",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        {children}
      </body>
    </html>
  );
}
